on: push
name: Publish Website over SFTP
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
        env:
          REPO: git@github.com:thomas-db/Sophrologie-Bordeaux.git
          BRANCH: master
          FOLDER: dist

  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          local-dir: ./dist/
          ftp-server: ftp://home538900693.1and1-data.host/ftptest
          ftp-username: u76543727-vt
          ftp-password: ${{ secrets.SFTP_PASSWORD }}
